<a href="https://colab.research.google.com/github/neklyud/programming_miem/blob/master/machine_learning2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np

In [0]:
train = np.zeros(shape = (3,4))
train[1,3] = 1.5
train[0,:] = 1.2
train[:,2] = 1.3
train = pd.DataFrame(train, columns=["x1", "x2", "y1", "y2"])            
print(train)

    x1   x2   y1   y2
0  1.2  1.2  1.3  1.2
1  0.0  0.0  1.3  1.5
2  0.0  0.0  1.3  0.0


In [41]:
selection = pd.read_csv("train.csv")
print(selection)

   Unnamed: 0   x1   x2   y1   y2
0           0  1.2  1.2  1.3  1.2
1           1  0.0  0.0  1.3  1.5
2           2  0.0  0.0  1.3  0.0


In [36]:
train = selection.to_numpy()
print(train)

[[0.  1.2 1.2 1.3 1.2]
 [1.  0.  0.  1.3 1.5]
 [2.  0.  0.  1.3 0. ]]


In [0]:
maths_string = []
for string in train:
  maths_string.append(sum(string)/len(string))
maths_cols = []
for string in train.transpose():
  maths_cols.append(sum(string)/len(string))


In [31]:
maths_string

[0.9800000000000001, 0.76, 0.6599999999999999]

In [32]:
maths_cols

[1.0, 0.39999999999999997, 0.39999999999999997, 1.3, 0.9]

In [0]:
train = pd.read_csv("dataset.csv", usecols = ["x1", "y"])


In [49]:
print(train.shape)
print(train[:5])

(100, 2)
         x1         y
0  0.312312 -0.240920
1  0.724806  1.355612
2  0.289753  0.757985
3  0.198513 -1.906744
4  0.894661  1.775589


In [0]:
train = train.to_numpy()

In [62]:
np.min(train,axis = 0)

array([ 0.01719159, -1.94408564])

In [66]:
train.min(axis=1)

array([-0.24092034,  0.72480556,  0.28975319, -1.90674408,  0.89466053,
        0.21655198, -1.27076358,  0.35624658, -0.2326398 ,  0.45276609,
        0.42755933,  0.04895592,  0.32476817,  0.77149058,  0.46993658,
        0.33169282,  0.65767364, -1.30157027,  0.58994929,  0.84185663,
        0.35319165,  0.60887904,  0.50285014, -0.11447591,  0.77066676,
        0.03870712,  0.83983561,  0.43789396,  0.91201002, -0.41238192,
        0.08650041,  0.41281935,  0.02378438,  0.70748674,  0.54535669,
        0.73185276,  0.11778847, -1.36232302,  0.01509431,  0.1395314 ,
        0.94069309, -0.1784116 , -0.63920259,  0.66281344,  0.59841311,
        0.17367376,  0.2083915 , -0.95864791, -0.9012177 , -0.08402153,
        0.71178817, -0.83530018, -0.08294407,  0.19206473, -1.24810844,
       -0.28259487, -0.78771552,  0.24008291, -0.86846543,  0.77702571,
        0.00294979,  0.57785553, -0.6927882 , -1.18333396, -0.61706695,
        0.90929667,  0.6204845 , -0.47984659,  0.68452061, -0.46

In [64]:
train.max(axis=1)

array([0.3123117 , 1.35561204, 0.75798509, 0.19851278, 1.77558878,
       0.98642889, 0.19916562, 0.7849871 , 0.90185445, 1.50463329,
       0.96513682, 2.02830273, 1.24573935, 1.29712391, 1.08743069,
       0.39645937, 1.59865408, 0.2019511 , 1.92916213, 1.0424836 ,
       0.93406325, 0.63108786, 1.11692132, 0.04579622, 0.84608824,
       0.21044904, 1.29663844, 2.3772725 , 2.16323475, 0.01719159,
       0.84265673, 1.2056051 , 0.55599746, 1.92746342, 0.81488607,
       0.9401926 , 0.56648749, 0.37555258, 0.03477017, 0.20278205,
       1.69885524, 0.18655451, 0.26317535, 1.09684291, 0.76129955,
       0.45859539, 1.16686309, 0.03530702, 0.09583437, 0.66855211,
       0.96172882, 0.74258472, 0.4568853 , 0.5540609 , 0.24159356,
       0.88278702, 0.02176953, 0.73391358, 0.03244539, 2.21188682,
       0.28864299, 0.60977847, 0.29377934, 0.7968742 , 0.23219042,
       0.92833319, 0.97024203, 0.12071355, 1.00981469, 0.99185601,
       1.34873725, 1.36274262, 0.07258132, 0.09029841, 0.51731

In [65]:
train.mean(axis=1)

array([ 0.03569568,  1.0402088 ,  0.52386914, -0.85411565,  1.33512465,
        0.60149044, -0.53579898,  0.57061684,  0.33460732,  0.97869969,
        0.69634807,  1.03862932,  0.78525376,  1.03430724,  0.77868363,
        0.3640761 ,  1.12816386, -0.54980959,  1.25955571,  0.94217012,
        0.64362745,  0.61998345,  0.80988573, -0.03433985,  0.8083775 ,
        0.12457808,  1.06823702,  1.40758323,  1.53762239, -0.19759517,
        0.46457857,  0.80921223,  0.28989092,  1.31747508,  0.68012138,
        0.83602268,  0.34213798, -0.49338522,  0.02493224,  0.17115672,
        1.31977416,  0.00407145, -0.18801362,  0.87982818,  0.67985633,
        0.31613457,  0.68762729, -0.46167044, -0.40269167,  0.29226529,
        0.83675849, -0.04635773,  0.18697061,  0.37306281, -0.50325744,
        0.30009608, -0.382973  ,  0.48699825, -0.41801002,  1.49445626,
        0.14579639,  0.593817  , -0.19950443, -0.19322988, -0.19243826,
        0.91881493,  0.79536326, -0.17956652,  0.84716765,  0.26

In [67]:
print("Min=", train.min(axis=0))
print("Max=", train.max(axis=0))
print("Mean=", train.mean(axis=0))

Min= [ 0.01719159 -1.94408564]
Max= [0.99185601 2.53136957]
Mean= [0.4909739 0.4809319]


In [0]:
train = pd.read_csv("dataset.csv", usecols = ["x1", "y"])


In [75]:
from sklearn.linear_model import LinearRegression
lr1 = LinearRegression()
lr1.fit(train[["x1"]], train[["y"]])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [76]:
print(lr1.coef_, lr1.intercept_)

[[1.31237048]] [-0.16340775]


In [81]:
from sklearn.metrics import r2_score
print(r2_score(train["y"], lr1.predict(train[["x1"]])))

0.1571066470728264


In [0]:
train2 = pd.read_csv("dataset2.csv")

In [88]:
print(r2_score(train2[["y"]], lr1.predict(train2[["x1"]])))

0.9038835667933462


7000

In [0]:
y = train[["y"]]
x = train.drop("y", axis=1)

In [0]:
from sklearn.model_selection import train_test_split
x_train, y_test, y_train, y_test = train_test_split(x,y,test_size = 0.3)

In [0]:
train = pd.read_csv("dataset4.csv", usecols = ["x1", "y"])

In [0]:
y = train[["y"]]
x = train.drop("y", axis=1)

In [0]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.3)


In [151]:
lr1 = LinearRegression()
lr1.fit(x_train, y_train)
print("lr1_coef=",lr1.coef_, "lr1_intercept=", lr1.intercept_)
print("r2_score_train=", r2_score(y_train, lr1.predict(x_train)))
print("r2_score_test=", r2_score(y_test, lr1.predict(x_test)))

lr1_coef= [[1.00524932]] lr1_intercept= [-0.00252488]
r2_score_train= 0.8949080468364232
r2_score_test= 0.8927999542831477


In [0]:
from sklearn.preprocessing import PolynomialFeatures

poly = PolynominalFeatures(2)
poly.fit_transform(x_train)